name: .NET Core

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  push-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Build with dotnet
      run: dotnet build --configuration Release
